package main

import (
	"fmt"

	"os"

	"log"

	"context"

	"github.com/vokuorg/skillrank"

	firebase "firebase.google.com/go"
  "google.golang.org/api/option"
)

func main() {
	graph := skillrank.NewGraph()

	// Use a service account
	ctx := context.Background()
	sa := option.WithCredentialsFile("./videovokodb-firebase-adminsdk-rvd1g-b154dac89c.json")
	app, err := firebase.NewApp(ctx, nil, sa)
	if err != nil {
		log.Fatalln(err)
	}

	client, err := app.Firestore(ctx)
	if err != nil {
		log.Fatalln(err)
	}
	defer client.Close()

	graph.Link(1, 2, "basic")
	graph.Link(1, 3, "advanced")
	graph.Link(1, 4, "intermediate")
	graph.Link(1, 5, "intermediate")
	graph.Link(1, 6, "advanced")
	graph.Link(1, 7, "advanced")
	graph.Link(1, 8, "basic")
	graph.Link(1, 9, "intermediate")
	graph.Link(1, 10, "intermediate")
	graph.Link(1, 11, "intermediate")
	graph.Link(1, 12, "advanced")
	graph.Link(1, 13, "advanced")
	graph.Link(1, 14, "intermediate")
	graph.Link(1, 15, "intermediate")
	graph.Link(1, 16, "basic")
	graph.Link(1, 17, "basic")
	graph.Link(1, 18, "intermediate")
	graph.Link(1, 19, "advanced")
	graph.Link(1, 20, "basic")
	graph.Link(2, 1, "intermediate")
	graph.Link(2, 3, "advanced")
	graph.Link(2, 4, "intermediate")
	graph.Link(2, 5, "intermediate")
	graph.Link(2, 6, "advanced")
	graph.Link(2, 7, "advanced")
	graph.Link(2, 8, "intermediate")
	graph.Link(2, 9, "intermediate")
	graph.Link(2, 10, "basic")
	graph.Link(2, 11, "basic")
	graph.Link(2, 12, "advanced")
	graph.Link(2, 13, "advanced")
	graph.Link(2, 14, "intermediate")
	graph.Link(2, 15, "advanced")
	graph.Link(2, 16, "intermediate")
	graph.Link(2, 17, "intermediate")
	graph.Link(2, 18, "intermediate")
	graph.Link(2, 19, "advanced")
	graph.Link(2, 20, "basic")
	graph.Link(3, 1, "intermediate")
	graph.Link(3, 2, "basic")
	graph.Link(3, 4, "advanced")
	graph.Link(3, 5, "intermediate")
	graph.Link(3, 6, "intermediate")
	graph.Link(3, 7, "advanced")
	graph.Link(3, 8, "basic")
	graph.Link(3, 9, "intermediate")
	graph.Link(3, 10, "intermediate")
	graph.Link(3, 11, "basic")
	graph.Link(3, 12, "advanced")
	graph.Link(3, 13, "advanced")
	graph.Link(3, 14, "intermediate")
	graph.Link(3, 15, "advanced")
	graph.Link(3, 16, "intermediate")
	graph.Link(3, 17, "basic")
	graph.Link(3, 18, "intermediate")
	graph.Link(3, 19, "advanced")
	graph.Link(3, 20, "basic")
	graph.Link(4, 1, "intermediate")
	graph.Link(4, 2, "basic")
	graph.Link(4, 3, "advanced")
	graph.Link(4, 5, "intermediate")
	graph.Link(4, 6, "intermediate")
	graph.Link(4, 7, "advanced")
	graph.Link(4, 8, "basic")
	graph.Link(4, 9, "intermediate")
	graph.Link(4, 10, "intermediate")
	graph.Link(4, 11, "basic")
	graph.Link(4, 12, "advanced")
	graph.Link(4, 13, "advanced")
	graph.Link(4, 14, "intermediate")
	graph.Link(4, 15, "intermediate")
	graph.Link(4, 16, "intermediate")
	graph.Link(4, 17, "basic")
	graph.Link(4, 18, "intermediate")
	graph.Link(4, 19, "advanced")
	graph.Link(4, 20, "basic")
	graph.Link(5, 1, "intermediate")
	graph.Link(5, 2, "basic")
	graph.Link(5, 3, "advanced")
	graph.Link(5, 4, "advanced")
	graph.Link(5, 6, "intermediate")
	graph.Link(5, 7, "intermediate")
	graph.Link(5, 8, "basic")
	graph.Link(5, 9, "intermediate")
	graph.Link(5, 10, "intermediate")
	graph.Link(5, 11, "basic")
	graph.Link(5, 12, "advanced")
	graph.Link(5, 13, "advanced")
	graph.Link(5, 14, "intermediate")
	graph.Link(5, 15, "intermediate")
	graph.Link(5, 16, "intermediate")
	graph.Link(5, 17, "basic")
	graph.Link(5, 18, "intermediate")
	graph.Link(5, 19, "advanced")
	graph.Link(5, 20, "intermediate")
	graph.Link(6, 1, "intermediate")
	graph.Link(6, 2, "basic")
	graph.Link(6, 3, "advanced")
	graph.Link(6, 4, "advanced")
	graph.Link(6, 5, "intermediate")
	graph.Link(6, 7, "advanced")
	graph.Link(6, 8, "basic")
	graph.Link(6, 9, "intermediate")
	graph.Link(6, 10, "intermediate")
	graph.Link(6, 11, "basic")
	graph.Link(6, 12, "advanced")
	graph.Link(6, 13, "advanced")
	graph.Link(6, 14, "intermediate")
	graph.Link(6, 15, "intermediate")
	graph.Link(6, 16, "intermediate")
	graph.Link(6, 17, "basic")
	graph.Link(6, 18, "intermediate")
	graph.Link(6, 19, "advanced")
	graph.Link(6, 20, "basic")
	graph.Link(7, 1, "intermediate")
	graph.Link(7, 2, "basic")
	graph.Link(7, 3, "advanced")
	graph.Link(7, 4, "advanced")
	graph.Link(7, 5, "intermediate")
	graph.Link(7, 6, "intermediate")
	graph.Link(7, 8, "basic")
	graph.Link(7, 9, "intermediate")
	graph.Link(7, 10, "intermediate")
	graph.Link(7, 11, "basic")
	graph.Link(7, 12, "advanced")
	graph.Link(7, 13, "advanced")
	graph.Link(7, 14, "intermediate")
	graph.Link(7, 15, "intermediate")
	graph.Link(7, 16, "intermediate")
	graph.Link(7, 17, "basic")
	graph.Link(7, 18, "intermediate")
	graph.Link(7, 19, "advanced")
	graph.Link(7, 20, "basic")
	graph.Link(8, 1, "intermediate")
	graph.Link(8, 2, "intermediate")
	graph.Link(8, 3, "intermediate")
	graph.Link(8, 4, "intermediate")
	graph.Link(8, 5, "intermediate")
	graph.Link(8, 6, "intermediate")
	graph.Link(8, 7, "advanced")
	graph.Link(8, 9, "intermediate")
	graph.Link(8, 10, "intermediate")
	graph.Link(8, 11, "basic")
	graph.Link(8, 12, "advanced")
	graph.Link(8, 13, "intermediate")
	graph.Link(8, 14, "intermediate")
	graph.Link(8, 15, "intermediate")
	graph.Link(8, 16, "intermediate")
	graph.Link(8, 17, "intermediate")
	graph.Link(8, 18, "intermediate")
	graph.Link(8, 19, "advanced")
	graph.Link(8, 20, "basic")
	graph.Link(9, 1, "intermediate")
	graph.Link(9, 2, "basic")
	graph.Link(9, 3, "advanced")
	graph.Link(9, 4, "advanced")
	graph.Link(9, 5, "intermediate")
	graph.Link(9, 6, "intermediate")
	graph.Link(9, 7, "advanced")
	graph.Link(9, 8, "basic")
	graph.Link(9, 10, "intermediate")
	graph.Link(9, 11, "basic")
	graph.Link(9, 12, "advanced")
	graph.Link(9, 13, "medium")
	graph.Link(9, 14, "intermediate")
	graph.Link(9, 15, "intermediate")
	graph.Link(9, 16, "intermediate")
	graph.Link(9, 17, "basic")
	graph.Link(9, 18, "intermediate")
	graph.Link(9, 19, "advanced")
	graph.Link(9, 20, "basic")
	graph.Link(10, 1, "intermediate")
	graph.Link(10, 2, "basic")
	graph.Link(10, 3, "advanced")
	graph.Link(10, 4, "advanced")
	graph.Link(10, 5, "intermediate")
	graph.Link(10, 6, "intermediate")
	graph.Link(10, 7, "advanced")
	graph.Link(10, 8, "basic")
	graph.Link(10, 9, "intermediate")
	graph.Link(10, 11, "basic")
	graph.Link(10, 12, "advanced")
	graph.Link(10, 13, "advanced")
	graph.Link(10, 14, "intermediate")
	graph.Link(10, 15, "intermediate")
	graph.Link(10, 16, "intermediate")
	graph.Link(10, 17, "basic")
	graph.Link(10, 18, "basic")
	graph.Link(10, 19, "advanced")
	graph.Link(10, 20, "basic")
	graph.Link(11, 1, "intermediate")
	graph.Link(11, 2, "basic")
	graph.Link(11, 3, "advanced")
	graph.Link(11, 4, "advanced")
	graph.Link(11, 5, "intermediate")
	graph.Link(11, 6, "advanced")
	graph.Link(11, 7, "advanced")
	graph.Link(11, 8, "basic")
	graph.Link(11, 9, "advanced")
	graph.Link(11, 10, "intermediate")
	graph.Link(11, 12, "advanced")
	graph.Link(11, 13, "advanced")
	graph.Link(11, 14, "intermediate")
	graph.Link(11, 15, "advanced")
	graph.Link(11, 16, "intermediate")
	graph.Link(11, 17, "basic")
	graph.Link(11, 18, "intermediate")
	graph.Link(11, 19, "advanced")
	graph.Link(11, 20, "basic")
	graph.Link(12, 1, "intermediate")
	graph.Link(12, 2, "basic")
	graph.Link(12, 3, "advanced")
	graph.Link(12, 4, "advanced")
	graph.Link(12, 5, "intermediate")
	graph.Link(12, 6, "intermediate")
	graph.Link(12, 7, "advanced")
	graph.Link(12, 8, "basic")
	graph.Link(12, 9, "intermediate")
	graph.Link(12, 10, "intermediate")
	graph.Link(12, 11, "basic")
	graph.Link(12, 13, "advanced")
	graph.Link(12, 14, "intermediate")
	graph.Link(12, 15, "intermediate")
	graph.Link(12, 16, "intermediate")
	graph.Link(12, 17, "basic")
	graph.Link(12, 18, "intermediate")
	graph.Link(12, 19, "advanced")
	graph.Link(12, 20, "basic")
	graph.Link(13, 1, "intermediate")
	graph.Link(13, 2, "basic")
	graph.Link(13, 3, "advanced")
	graph.Link(13, 4, "advanced")
	graph.Link(13, 5, "intermediate")
	graph.Link(13, 6, "intermediate")
	graph.Link(13, 7, "advanced")
	graph.Link(13, 8, "basic")
	graph.Link(13, 9, "intermediate")
	graph.Link(13, 10, "intermediate")
	graph.Link(13, 11, "basic")
	graph.Link(13, 12, "advanced")
	graph.Link(13, 14, "intermediate")
	graph.Link(13, 15, "intermediate")
	graph.Link(13, 16, "intermediate")
	graph.Link(13, 17, "basic")
	graph.Link(13, 18, "intermediate")
	graph.Link(13, 19, "advanced")
	graph.Link(13, 20, "basic")
	graph.Link(14, 1, "intermediate")
	graph.Link(14, 2, "basic")
	graph.Link(14, 3, "advanced")
	graph.Link(14, 4, "advanced")
	graph.Link(14, 5, "intermediate")
	graph.Link(14, 6, "intermediate")
	graph.Link(14, 7, "advanced")
	graph.Link(14, 8, "basic")
	graph.Link(14, 9, "intermediate")
	graph.Link(14, 10, "intermediate")
	graph.Link(14, 11, "intermediate")
	graph.Link(14, 12, "advanced")
	graph.Link(14, 13, "advanced")
	graph.Link(14, 15, "advanced")
	graph.Link(14, 16, "intermediate")
	graph.Link(14, 17, "basic")
	graph.Link(14, 18, "intermediate")
	graph.Link(14, 19, "advanced")
	graph.Link(14, 20, "basic")
	graph.Link(15, 1, "intermediate")
	graph.Link(15, 2, "basic")
	graph.Link(15, 3, "advanced")
	graph.Link(15, 4, "advanced")
	graph.Link(15, 5, "intermediate")
	graph.Link(15, 6, "intermediate")
	graph.Link(15, 7, "advanced")
	graph.Link(15, 8, "basic")
	graph.Link(15, 9, "intermediate")
	graph.Link(15, 10, "intermediate")
	graph.Link(15, 11, "basic")
	graph.Link(15, 12, "advanced")
	graph.Link(15, 13, "advanced")
	graph.Link(15, 14, "intermediate")
	graph.Link(15, 16, "intermediate")
	graph.Link(15, 17, "basic")
	graph.Link(15, 18, "intermediate")
	graph.Link(15, 19, "advanced")
	graph.Link(15, 20, "basic")
	graph.Link(16, 1, "intermediate")
	graph.Link(16, 2, "basic")
	graph.Link(16, 3, "advanced")
	graph.Link(16, 4, "advanced")
	graph.Link(16, 5, "basic")
	graph.Link(16, 6, "intermediate")
	graph.Link(16, 7, "advanced")
	graph.Link(16, 8, "basic")
	graph.Link(16, 9, "intermediate")
	graph.Link(16, 10, "advanced")
	graph.Link(16, 11, "basic")
	graph.Link(16, 12, "advanced")
	graph.Link(16, 13, "advanced")
	graph.Link(16, 14, "intermediate")
	graph.Link(16, 15, "intermediate")
	graph.Link(16, 17, "basic")
	graph.Link(16, 18, "intermediate")
	graph.Link(16, 19, "advanced")
	graph.Link(16, 20, "basic")
	graph.Link(17, 1, "intermediate")
	graph.Link(17, 2, "basic")
	graph.Link(17, 3, "intermediate")
	graph.Link(17, 4, "advanced")
	graph.Link(17, 5, "intermediate")
	graph.Link(17, 6, "intermediate")
	graph.Link(17, 7, "advanced")
	graph.Link(17, 8, "intermediate")
	graph.Link(17, 9, "advanced")
	graph.Link(17, 10, "intermediate")
	graph.Link(17, 11, "basic")
	graph.Link(17, 12, "advanced")
	graph.Link(17, 13, "advanced")
	graph.Link(17, 14, "advanced")
	graph.Link(17, 15, "intermediate")
	graph.Link(17, 16, "intermediate")
	graph.Link(17, 18, "intermediate")
	graph.Link(17, 19, "advanced")
	graph.Link(17, 20, "basic")
	graph.Link(18, 1, "intermediate")
	graph.Link(18, 2, "basic")
	graph.Link(18, 3, "advanced")
	graph.Link(18, 4, "advanced")
	graph.Link(18, 5, "intermediate")
	graph.Link(18, 6, "intermediate")
	graph.Link(18, 7, "advanced")
	graph.Link(18, 8, "basic")
	graph.Link(18, 9, "intermediate")
	graph.Link(18, 10, "intermediate")
	graph.Link(18, 11, "basic")
	graph.Link(18, 12, "advanced")
	graph.Link(18, 13, "advanced")
	graph.Link(18, 14, "intermediate")
	graph.Link(18, 15, "intermediate")
	graph.Link(18, 16, "intermediate")
	graph.Link(18, 17, "basic")
	graph.Link(18, 19, "advanced")
	graph.Link(18, 20, "basic")
	graph.Link(19, 1, "intermediate")
	graph.Link(19, 2, "basic")
	graph.Link(19, 3, "advanced")
	graph.Link(19, 4, "advanced")
	graph.Link(19, 5, "intermediate")
	graph.Link(19, 6, "intermediate")
	graph.Link(19, 7, "advanced")
	graph.Link(19, 8, "basic")
	graph.Link(19, 9, "intermediate")
	graph.Link(19, 10, "intermediate")
	graph.Link(19, 11, "basic")
	graph.Link(19, 12, "advanced")
	graph.Link(19, 13, "advanced")
	graph.Link(19, 14, "intermediate")
	graph.Link(19, 15, "intermediate")
	graph.Link(19, 16, "intermediate")
	graph.Link(19, 17, "basic")
	graph.Link(19, 18, "intermediate")
	graph.Link(19, 20, "basic")
	graph.Link(20, 1, "intermediate")
	graph.Link(20, 2, "basic")
	graph.Link(20, 3, "advanced")
	graph.Link(20, 4, "advanced")
	graph.Link(20, 5, "intermediate")
	graph.Link(20, 6, "advanced")
	graph.Link(20, 7, "advanced")
	graph.Link(20, 8, "basic")
	graph.Link(20, 9, "advanced")
	graph.Link(20, 10, "intermediate")
	graph.Link(20, 11, "basic")
	graph.Link(20, 12, "advanced")
	graph.Link(20, 13, "advanced")
	graph.Link(20, 14, "advanced")
	graph.Link(20, 15, "intermediate")
	graph.Link(20, 16, "advanced")
	graph.Link(20, 17, "basic")
	graph.Link(20, 18, "intermediate")
	graph.Link(20, 19, "advanced")

	ranking := graph.RankInJSON(0.85, 0.000001)
	fmt.Println(ranking)

	f, err := os.Create("ranking.json")

	if err != nil {
			log.Fatal(err)
	}

	defer f.Close()

	_, err2 := f.WriteString(ranking)

	if err2 != nil {
			log.Fatal(err2)
	}

	// Write ranking to Firestore
	client.Collection("statistics").Add(ctx, map[string]interface{}{
			"ranking": ranking,
	})
}